### ISSUE TITLE
iOS : invalid encrypted key

### ISSUE THREAD

**Issue by NikunjRajyaguru** [pkuoliver/EasyAES#1]
Hello,

I have implement this lib. into my project and its working nice for Android and PHP platform but having some issue with iOS swift i.e, iOS generated encrypted key is invalid for other platforms.

Well below have shown, how my code looks like:

- let str = "This is test"

- let data = str.data(using: .utf8)   ///Converting string to Data

- let encrypData = data.aes128Encrypt(withKey: IV_KEY_REVERSED, iv: IV_KEY) 

print("**** \(String(data: encrypData!, encoding: .utf8))") /// Gettting invalid encrypted value

Please let me know, if anything wrong in my code or missing.

Thanks in advance.

**Comment by pkuoliver** [comment]
i didn't test the code for swift(i'm not familiar with swift). Can you call the function in object-c?
i guess maybe they use not **real-same** system lib for object-c and swift.

**Comment by pkuoliver** [comment]
No response for several years.
