### ISSUE TITLE
My AES Encryption string is different with android and php code 

### ISSUE THREAD

**Issue by cavoixanh** [pkuoliver/EasyAES#2]
NSData * data = [@"12345678" dataUsingEncoding:NSUTF8StringEncoding allowLossyConversion:NO];
    NSData * encode = [data AES128EncryptWithKey:@"abcdefgh" iv:@""];
    NSString * temp = [encode base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed];
    NSLog(@"%@",temp);

I tried with this code from objective C. Php and android have same result but objective C is different. Please help

**Comment by pkuoliver** [comment]
iv parameter can not be empty, and passward must 16 characters.
